# Funding configuration
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# GitHub Sponsors
github: [AishwaryShrivastav]

# Other platforms (uncomment when available)
# patreon: your_patreon
# open_collective: ai-first-design-system
# ko_fi: your_kofi
# custom: ["https://your-website.com/donate"]

