import type { Meta, StoryObj } from '@storybook/web-components';
import { html } from 'lit';
import 'ai-first-design-system/components/ai/ai-label';

/**
 * AI label component to clearly mark AI-generated content.
 *
 * ## Features
 * - Clear visual indicator for AI content
 * - Optional model name display
 * - Interactive variant for more information
 * - Subtle animation option
 * - Gradient background
 *
 * ## Accessibility
 * - Clear visual indicator
 * - Screen reader friendly
 * - Keyboard accessible when interactive
 *
 * ## References
 * - [IBM Carbon for AI Labels](https://carbondesignsystem.com/guidelines/carbon-for-ai/)
 * - AI transparency best practices from [Microsoft HAX](https://www.microsoft.com/en-us/haxtoolkit/ai-guidelines/)
 * - [WCAG 2.2 Visual Indicators](https://www.w3.org/WAI/WCAG22/Understanding/visual-indicators)
 */
const meta: Meta = {
  title: 'AI Components/Label',
  component: 'ai-label',
  tags: ['autodocs'],
  argTypes: {
    interactive: {
      control: 'boolean',
      description: 'Make label clickable for more info',
    },
    model: {
      control: 'text',
      description: 'AI model name to display',
    },
    animated: {
      control: 'boolean',
      description: 'Enable subtle animation',
    },
  },
};

export default meta;
type Story = StoryObj;

export const Default: Story = {
  args: {},
  render: args =>
    html`<ai-label
      ?interactive=${args.interactive}
      model=${args.model || ''}
      ?animated=${args.animated}
    >
      AI Generated
    </ai-label>`,
};

export const Basic: Story = {
  render: () => html`<ai-label>AI Generated</ai-label>`,
};

export const WithModel: Story = {
  render: () => html`<ai-label model="GPT-4">Generated by AI</ai-label>`,
};

export const Interactive: Story = {
  args: {
    interactive: true,
  },
  render: args =>
    html`<ai-label ?interactive=${args.interactive} model="GPT-4"> Click for details </ai-label>`,
};

export const Animated: Story = {
  args: {
    animated: true,
  },
  render: args => html`<ai-label ?animated=${args.animated} model="Claude">AI Content</ai-label>`,
};

export const Static: Story = {
  args: {
    animated: false,
  },
  render: args =>
    html`<ai-label ?animated=${args.animated} model="GPT-3.5">AI Generated</ai-label>`,
};

export const DifferentModels: Story = {
  render: () => html`
    <div style="display: flex; gap: 0.75rem; flex-wrap: wrap; align-items: center;">
      <ai-label model="GPT-4">GPT-4</ai-label>
      <ai-label model="Claude">Claude</ai-label>
      <ai-label model="Gemini">Gemini</ai-label>
      <ai-label model="LLaMA">LLaMA</ai-label>
    </div>
  `,
};

export const InteractiveVariants: Story = {
  render: () => html`
    <div style="display: flex; flex-direction: column; gap: 1rem;">
      <div>
        <p style="margin: 0 0 0.5rem 0; font-size: 0.875rem; color: #6b7280;">Non-interactive:</p>
        <ai-label model="GPT-4">AI Generated Content</ai-label>
      </div>

      <div>
        <p style="margin: 0 0 0.5rem 0; font-size: 0.875rem; color: #6b7280;">
          Interactive (clickable):
        </p>
        <ai-label interactive model="GPT-4">AI Generated Content</ai-label>
      </div>
    </div>
  `,
};

export const RealWorldExamples: Story = {
  render: () => html`
    <div style="display: flex; flex-direction: column; gap: 1.5rem; max-width: 500px;">
      <div
        style="padding: 1rem; background: white; border: 1px solid #e5e7eb; border-radius: 0.5rem;"
      >
        <div
          style="display: flex; justify-content: space-between; align-items: start; margin-bottom: 0.5rem;"
        >
          <h3 style="margin: 0; font-size: 1rem; font-weight: 600;">Article Title</h3>
          <ai-label model="GPT-4">AI</ai-label>
        </div>
        <p style="margin: 0; color: #6b7280; font-size: 0.875rem;">
          This article was generated by AI and reviewed by human editors.
        </p>
      </div>

      <div
        style="padding: 1rem; background: white; border: 1px solid #e5e7eb; border-radius: 0.5rem;"
      >
        <div
          style="display: flex; justify-content: space-between; align-items: start; margin-bottom: 0.5rem;"
        >
          <h3 style="margin: 0; font-size: 1rem; font-weight: 600;">Code Suggestion</h3>
          <ai-label interactive model="GitHub Copilot">AI</ai-label>
        </div>
        <pre
          style="margin: 0; padding: 0.75rem; background: #f9fafb; border-radius: 0.25rem; font-size: 0.875rem;"
        ><code>function example() {
  // AI-generated code
}</code></pre>
      </div>

      <div
        style="padding: 1rem; background: white; border: 1px solid #e5e7eb; border-radius: 0.5rem;"
      >
        <div
          style="display: flex; justify-content: space-between; align-items: start; margin-bottom: 0.5rem;"
        >
          <h3 style="margin: 0; font-size: 1rem; font-weight: 600;">Image Description</h3>
          <ai-label animated model="DALL-E">AI</ai-label>
        </div>
        <p style="margin: 0; color: #6b7280; font-size: 0.875rem;">
          Image description generated by AI vision model.
        </p>
      </div>
    </div>
  `,
};

export const AllVariants: Story = {
  render: () => html`
    <div style="display: flex; flex-direction: column; gap: 1rem;">
      <div>
        <h4 style="margin: 0 0 0.5rem 0; font-size: 0.875rem; font-weight: 600;">Basic</h4>
        <ai-label>AI Generated</ai-label>
      </div>

      <div>
        <h4 style="margin: 0 0 0.5rem 0; font-size: 0.875rem; font-weight: 600;">With Model</h4>
        <ai-label model="GPT-4">AI Generated</ai-label>
      </div>

      <div>
        <h4 style="margin: 0 0 0.5rem 0; font-size: 0.875rem; font-weight: 600;">Interactive</h4>
        <ai-label interactive model="GPT-4">AI Generated</ai-label>
      </div>

      <div>
        <h4 style="margin: 0 0 0.5rem 0; font-size: 0.875rem; font-weight: 600;">
          Animated (default)
        </h4>
        <ai-label animated model="Claude">AI Generated</ai-label>
      </div>

      <div>
        <h4 style="margin: 0 0 0.5rem 0; font-size: 0.875rem; font-weight: 600;">Static</h4>
        <ai-label animated="false" model="Gemini">AI Generated</ai-label>
      </div>
    </div>
  `,
};
