import type { Meta, StoryObj } from '@storybook/web-components';
import { html } from 'lit';
import 'ai-first-design-system/components/ai/ai-tooltip';
import 'ai-first-design-system/components/base/ai-button';

/**
 * AI Tooltip Component
 *
 * Contextual tooltip component optimized for AI explanations and guidance.
 * Supports rich content, AI-specific styling, progressive disclosure,
 * and interaction tracking for AI help systems.
 *
 * ## Features
 * - Multiple trigger modes: hover, click, focus, manual
 * - AI explanation styling
 * - Rich content support
 * - Learn More links
 * - Dismissible option
 * - Multiple placements
 * - Customizable delay
 *
 * ## Accessibility
 * - role="tooltip" with proper ARIA relationships
 * - Keyboard accessible
 * - Escape key dismisses tooltip
 * - Screen reader compatible
 *
 * ## References
 * - WAI-ARIA Tooltip Pattern
 * - IBM Carbon Tooltip (2024): Design patterns
 * - [Microsoft HAX #7](https://www.microsoft.com/en-us/haxtoolkit/ai-guidelines/): Explain AI decisions
 * - SAP Fiori Explainable AI: Contextual explanations
 */
const meta: Meta = {
  title: 'AI Components/Tooltip',
  component: 'ai-tooltip',
  tags: ['autodocs'],
  argTypes: {
    content: {
      control: 'text',
      description: 'Tooltip text content',
    },
    placement: {
      control: 'select',
      options: ['top', 'bottom', 'left', 'right'],
      description: 'Tooltip placement',
    },
    trigger: {
      control: 'select',
      options: ['hover', 'click', 'focus', 'manual'],
      description: 'How to trigger the tooltip',
    },
    delay: {
      control: { type: 'number', min: 0, step: 100 },
      description: 'Show delay in milliseconds',
    },
    aiExplanation: {
      control: 'boolean',
      description: 'Style as AI explanation',
    },
    learnMoreUrl: {
      control: 'text',
      description: 'URL for Learn More link',
    },
    dismissible: {
      control: 'boolean',
      description: 'Show dismiss button',
    },
    maxWidth: {
      control: { type: 'number', min: 100, max: 500 },
      description: 'Maximum width in pixels',
    },
  },
};

export default meta;
type Story = StoryObj;

export const Default: Story = {
  args: {
    content: 'This is a helpful tooltip',
    placement: 'top',
  },
  render: args => html`
    <div style="padding: 4rem; display: flex; justify-content: center;">
      <ai-tooltip
        content=${args.content}
        placement=${args.placement}
        trigger=${args.trigger || 'hover'}
        delay=${args.delay || 200}
        ?aiExplanation=${args.aiExplanation}
        learnMoreUrl=${args.learnMoreUrl || ''}
        ?dismissible=${args.dismissible}
        maxWidth=${args.maxWidth || 280}
      >
        <ai-button>Hover me</ai-button>
      </ai-tooltip>
    </div>
  `,
};

export const Placements: Story = {
  render: () => html`
    <div
      style="padding: 6rem; display: grid; grid-template-columns: repeat(3, 1fr); gap: 2rem; justify-items: center;"
    >
      <div></div>
      <ai-tooltip content="Tooltip on top" placement="top">
        <ai-button>Top</ai-button>
      </ai-tooltip>
      <div></div>

      <ai-tooltip content="Tooltip on left" placement="left">
        <ai-button>Left</ai-button>
      </ai-tooltip>
      <div></div>
      <ai-tooltip content="Tooltip on right" placement="right">
        <ai-button>Right</ai-button>
      </ai-tooltip>

      <div></div>
      <ai-tooltip content="Tooltip on bottom" placement="bottom">
        <ai-button>Bottom</ai-button>
      </ai-tooltip>
      <div></div>
    </div>
  `,
};

export const AIExplanation: Story = {
  render: () => html`
    <div
      style="padding: 4rem; display: flex; flex-direction: column; gap: 2rem; align-items: center;"
    >
      <ai-tooltip
        content="AI analyzed your preferences and usage patterns to suggest this option. The recommendation is based on similar users who had positive outcomes."
        placement="top"
        aiExplanation
      >
        <ai-button aiGenerated confidence="0.92">AI Suggested Action</ai-button>
      </ai-tooltip>

      <ai-tooltip
        content="This content was generated by AI. While we strive for accuracy, please verify important information."
        placement="bottom"
        aiExplanation
        learnMoreUrl="https://example.com/ai-transparency"
      >
        <span
          style="padding: 0.5rem 1rem; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; border-radius: 0.375rem; cursor: help;"
        >
          AI Generated Content ✨
        </span>
      </ai-tooltip>
    </div>
  `,
};

export const WithLearnMore: Story = {
  render: () => html`
    <div style="padding: 4rem; display: flex; justify-content: center;">
      <ai-tooltip
        content="This feature uses machine learning to predict the best outcomes based on historical data."
        placement="top"
        aiExplanation
        learnMoreUrl="https://example.com/learn-more"
      >
        <ai-button variant="secondary">
          <span>AI Prediction</span>
          <span style="margin-left: 0.25rem; font-size: 0.75rem;">ℹ️</span>
        </ai-button>
      </ai-tooltip>
    </div>
  `,
};

export const Dismissible: Story = {
  render: () => html`
    <div style="padding: 4rem; display: flex; justify-content: center;">
      <ai-tooltip
        content="This is a detailed explanation that you might want to dismiss after reading. The tooltip will stay visible until you click the X button."
        placement="top"
        aiExplanation
        dismissible
        trigger="click"
      >
        <ai-button>Click for Info</ai-button>
      </ai-tooltip>
    </div>
  `,
};

export const TriggerModes: Story = {
  render: () => html`
    <div style="padding: 4rem; display: flex; gap: 2rem; justify-content: center; flex-wrap: wrap;">
      <ai-tooltip content="Shows on hover (default)" placement="top" trigger="hover">
        <ai-button>Hover Trigger</ai-button>
      </ai-tooltip>

      <ai-tooltip content="Shows on click" placement="top" trigger="click">
        <ai-button variant="secondary">Click Trigger</ai-button>
      </ai-tooltip>

      <ai-tooltip content="Shows on focus (tab to this button)" placement="top" trigger="focus">
        <ai-button variant="ghost">Focus Trigger</ai-button>
      </ai-tooltip>
    </div>
  `,
};

export const CustomDelay: Story = {
  render: () => html`
    <div style="padding: 4rem; display: flex; gap: 2rem; justify-content: center;">
      <ai-tooltip content="Instant tooltip (0ms delay)" placement="top" delay="0">
        <ai-button>No Delay</ai-button>
      </ai-tooltip>

      <ai-tooltip content="Default delay (200ms)" placement="top" delay="200">
        <ai-button variant="secondary">Default Delay</ai-button>
      </ai-tooltip>

      <ai-tooltip content="Slow tooltip (500ms delay)" placement="top" delay="500">
        <ai-button variant="ghost">Slow Delay</ai-button>
      </ai-tooltip>
    </div>
  `,
};

export const RichContent: Story = {
  render: () => html`
    <div style="padding: 4rem; display: flex; justify-content: center;">
      <ai-tooltip
        placement="top"
        aiExplanation
        learnMoreUrl="https://example.com/docs"
        dismissible
        trigger="click"
        maxWidth="320"
      >
        <ai-button>View AI Analysis</ai-button>
        <div slot="content">
          <div style="margin-bottom: 0.75rem;">
            <strong style="display: block; margin-bottom: 0.25rem;">Confidence Breakdown</strong>
            <ul style="margin: 0; padding-left: 1rem; font-size: 0.75rem; opacity: 0.9;">
              <li>Data Quality: 95%</li>
              <li>Pattern Match: 87%</li>
              <li>Historical Accuracy: 91%</li>
            </ul>
          </div>
          <div style="font-size: 0.75rem; opacity: 0.7;">Based on 1,247 similar cases</div>
        </div>
      </ai-tooltip>
    </div>
  `,
};

export const RealWorldExamples: Story = {
  render: () => html`
    <div
      style="padding: 4rem; display: flex; flex-direction: column; gap: 3rem; align-items: center;"
    >
      <div>
        <h4 style="margin: 0 0 1rem 0; text-align: center; font-size: 0.875rem; color: #6b7280;">
          AI Feature Explanation
        </h4>
        <ai-tooltip
          content="Smart Sort uses machine learning to order results based on your past interactions, preferences, and similar users' behavior."
          placement="right"
          aiExplanation
          learnMoreUrl="https://example.com/smart-sort"
        >
          <div
            style="display: flex; align-items: center; gap: 0.5rem; padding: 0.75rem 1rem; background: #f9fafb; border-radius: 0.375rem; cursor: help;"
          >
            <span>🧠 Smart Sort</span>
            <span style="font-size: 0.75rem; color: #6b7280;">?</span>
          </div>
        </ai-tooltip>
      </div>

      <div>
        <h4 style="margin: 0 0 1rem 0; text-align: center; font-size: 0.875rem; color: #6b7280;">
          Confidence Indicator
        </h4>
        <ai-tooltip
          content="AI is 87% confident in this recommendation. Lower confidence may indicate the need for human review."
          placement="top"
          aiExplanation
        >
          <div
            style="display: inline-flex; align-items: center; gap: 0.5rem; padding: 0.5rem 0.75rem; background: #fef3c7; border-radius: 0.25rem; font-size: 0.875rem; cursor: help;"
          >
            <span style="color: #d97706;">⚠️ 87% Confidence</span>
          </div>
        </ai-tooltip>
      </div>

      <div>
        <h4 style="margin: 0 0 1rem 0; text-align: center; font-size: 0.875rem; color: #6b7280;">
          AI-Generated Badge
        </h4>
        <ai-tooltip
          content="This text was created by AI based on your brief. Always review AI-generated content before publishing."
          placement="bottom"
          aiExplanation
          dismissible
          trigger="click"
        >
          <span
            style="display: inline-flex; align-items: center; gap: 0.375rem; padding: 0.25rem 0.5rem; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; font-size: 0.75rem; border-radius: 9999px; cursor: pointer;"
          >
            ✨ AI Generated
          </span>
        </ai-tooltip>
      </div>

      <div>
        <h4 style="margin: 0 0 1rem 0; text-align: center; font-size: 0.875rem; color: #6b7280;">
          Data Source Attribution
        </h4>
        <ai-tooltip
          content="This insight was derived from analyzing 3,456 customer records from the past 90 days. The model considers purchase history, browsing behavior, and demographic data."
          placement="top"
          aiExplanation
          learnMoreUrl="https://example.com/methodology"
          maxWidth="320"
        >
          <ai-button variant="ghost" style="text-decoration: underline;">
            How did AI determine this?
          </ai-button>
        </ai-tooltip>
      </div>
    </div>
  `,
};

export const FormFieldHelp: Story = {
  render: () => html`
    <div style="padding: 4rem; max-width: 400px; margin: 0 auto;">
      <div style="margin-bottom: 1.5rem;">
        <div style="display: flex; align-items: center; gap: 0.5rem; margin-bottom: 0.5rem;">
          <label style="font-weight: 500; font-size: 0.875rem;">AI Temperature</label>
          <ai-tooltip
            content="Temperature controls randomness in AI responses. Lower values (0.0-0.3) produce more focused, deterministic outputs. Higher values (0.7-1.0) increase creativity and variation."
            placement="right"
            aiExplanation
            learnMoreUrl="https://example.com/ai-parameters"
          >
            <span
              style="width: 1rem; height: 1rem; display: inline-flex; align-items: center; justify-content: center; background: #e5e7eb; border-radius: 50%; font-size: 0.625rem; cursor: help;"
              >?</span
            >
          </ai-tooltip>
        </div>
        <input type="range" min="0" max="1" step="0.1" value="0.7" style="width: 100%;" />
        <div
          style="display: flex; justify-content: space-between; font-size: 0.75rem; color: #6b7280;"
        >
          <span>Focused</span>
          <span>Creative</span>
        </div>
      </div>

      <div>
        <div style="display: flex; align-items: center; gap: 0.5rem; margin-bottom: 0.5rem;">
          <label style="font-weight: 500; font-size: 0.875rem;">Max Tokens</label>
          <ai-tooltip
            content="Maximum number of tokens (roughly words) the AI can generate. Higher limits allow longer responses but increase processing time and cost."
            placement="right"
            aiExplanation
          >
            <span
              style="width: 1rem; height: 1rem; display: inline-flex; align-items: center; justify-content: center; background: #e5e7eb; border-radius: 50%; font-size: 0.625rem; cursor: help;"
              >?</span
            >
          </ai-tooltip>
        </div>
        <input
          type="number"
          value="2048"
          style="width: 100%; padding: 0.5rem; border: 1px solid #e5e7eb; border-radius: 0.375rem;"
        />
      </div>
    </div>
  `,
};
