import { LitElement, html, css, TemplateResult } from 'lit';
import { customElement, property } from 'lit/decorators.js';

/**
 * AI label component to clearly mark AI-generated content.
 *
 * @element ai-label
 *
 * @fires click - Dispatched when label is clicked (if interactive)
 *
 * @slot - Label text (defaults to "AI Generated")
 *
 * @cssprop --ai-label-bg - Background gradient
 * @cssprop --ai-label-color - Text color
 *
 * @prop {boolean} interactive - Make label clickable for more info
 * @prop {string} model - AI model name to display
 * @prop {boolean} animated - Enable subtle animation
 *
 * @example
 * ```html
 * <ai-label>AI Generated</ai-label>
 * <ai-label interactive model="GPT-4">Generated by AI</ai-label>
 * ```
 *
 * @accessibility
 * - Clear visual indicator
 * - Screen reader friendly
 * - Keyboard accessible when interactive
 *
 * @reference
 * - IBM Carbon for AI labels: https://carbondesignsystem.com/guidelines/carbon-for-ai/
 * - AI transparency best practices from Microsoft HAX
 */
@customElement('ai-label')
export class AILabel extends LitElement {
  @property({ type: Boolean }) interactive = false;
  @property({ type: String }) model = '';
  @property({ type: Boolean }) animated = true;

  static styles = css`
    :host {
      display: inline-block;
    }

    .ai-label {
      display: inline-flex;
      align-items: center;
      gap: 0.375rem;
      padding: 0.25rem 0.625rem;
      border-radius: 0.375rem;
      font-size: 0.75rem;
      font-weight: 500;
      background: var(--ai-label-bg, linear-gradient(135deg, #667eea 0%, #764ba2 100%));
      color: var(--ai-label-color, white);
      cursor: default;
      user-select: none;
    }

    :host([interactive]) .ai-label {
      cursor: pointer;
      transition: all 150ms ease;
    }

    :host([interactive]) .ai-label:hover {
      transform: translateY(-1px);
      box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
    }

    :host([interactive]) .ai-label:focus-visible {
      outline: 2px solid currentColor;
      outline-offset: 2px;
    }

    .ai-icon {
      width: 1rem;
      height: 1rem;
      background: rgba(255, 255, 255, 0.3);
      border-radius: 0.25rem;
      display: flex;
      align-items: center;
      justify-content: center;
      font-size: 0.625rem;
    }

    :host([animated]) .ai-icon {
      animation: pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite;
    }

    @keyframes pulse {
      0%,
      100% {
        opacity: 1;
      }
      50% {
        opacity: 0.6;
      }
    }

    .model-info {
      font-size: 0.625rem;
      opacity: 0.9;
      padding-left: 0.375rem;
      border-left: 1px solid rgba(255, 255, 255, 0.3);
    }
  `;

  private _handleClick() {
    if (this.interactive) {
      this.dispatchEvent(
        new CustomEvent('click', {
          bubbles: true,
          composed: true,
          detail: { model: this.model },
        })
      );
    }
  }

  render(): TemplateResult {
    return html`
      <span
        class="ai-label"
        part="label"
        role=${this.interactive ? 'button' : 'status'}
        tabindex=${this.interactive ? '0' : undefined}
        @click=${this._handleClick}
        @keydown=${(e: KeyboardEvent) => {
          if (this.interactive && (e.key === 'Enter' || e.key === ' ')) {
            e.preventDefault();
            this._handleClick();
          }
        }}
      >
        <span class="ai-icon">✨</span>
        <slot>AI Generated</slot>
        ${this.model ? html`<span class="model-info">${this.model}</span>` : ''}
      </span>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'ai-label': AILabel;
  }
}
