/**
 * Build script to generate CSS variables from design tokens
 * 
 * This script generates a CSS file with CSS custom properties
 * from the TypeScript token definitions.
 */

import { writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Import tokens (they're already compiled to JS by tsc)
import { colors } from './dist/colors.js';
import { spacing } from './dist/spacing.js';
import { typography } from './dist/typography.js';
import { shadows } from './dist/shadows.js';
import { aiTokens } from './dist/ai-tokens.js';

/**
 * Convert object to CSS custom properties
 */
function toCSSVars(obj, prefix = '') {
  let css = '';
  
  for (const [key, value] of Object.entries(obj)) {
    const varName = prefix ? `${prefix}-${key}` : key;
    
    if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
      // Recursively process nested objects
      css += toCSSVars(value, varName);
    } else {
      // Convert kebab-case for CSS
      const cssVarName = varName.replace(/([A-Z])/g, '-$1').toLowerCase();
      css += `  --ai-${cssVarName}: ${value};\n`;
    }
  }
  
  return css;
}

// Generate CSS
let css = `/**
 * AI-First Design System - CSS Custom Properties
 * 
 * Auto-generated from design tokens.
 * Do not edit this file directly.
 * 
 * @generated
 */

:root {
${toCSSVars(colors, 'color')}
${toCSSVars(spacing, 'spacing')}
${toCSSVars(typography, 'typography')}
${toCSSVars(shadows, 'shadow')}
${toCSSVars(aiTokens, 'ai')}
}
`;

// Write to dist/tokens.css
const outputPath = join(__dirname, 'dist', 'tokens.css');
writeFileSync(outputPath, css, 'utf-8');

console.log('✓ Generated tokens.css');

